SEP490_G41/AR_Navigation/Pages/Buildings/detail.cshtml.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Buildings
{
    public class DetailModel : PageModel
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<listModel> _logger;


        public DetailModel(IWebHostEnvironment webHostEnvironment, ILogger<listModel> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        public void OnGet([FromRoute] int id)
        {
            Id = id;
        }
        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public async Task<IActionResult> OnPostAddOrEditMapAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Map");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Buildings/Detail", new { id = Id });
        }

        public async Task<IActionResult> OnPostEditMappointMapAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Map");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");

            return RedirectToPage("/Buildings/Detail", new { id = Id });

        }
    }
}

SEP490_G41/AR_Navigation/Pages/Buildings/list.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Buildings
{
    public class listModel : PageModel
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<listModel> _logger;


        public listModel(IWebHostEnvironment webHostEnvironment, ILogger<listModel> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public async Task<IActionResult> OnPostCreateBuildingAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Building");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Buildings/list");
        }

        public async Task<IActionResult> OnPostEditBuildingAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Building");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Buildings/list");
        }
    }
}

SEP490_G41/AR_Navigation/Pages/Mappoints/detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Mappoints
{
    public class detailModel : PageModel
    {

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<listModel> _logger;


        public detailModel(IWebHostEnvironment webHostEnvironment, ILogger<listModel> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }
        public void OnGet([FromRoute] int id)
        {
            Id = id;
        }
        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public async Task<IActionResult> OnPostEditMappointAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Mappoint");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Mappoints/detail", new { id = Id });
        }

     
    }
}

SEP490_G41/AR_Navigation/Pages/Mappoints/list.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Mappoints
{
    public class listModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SEP490_G41/AR_Navigation/Pages/Maps/detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Maps
{
    public class detailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SEP490_G41/AR_Navigation/Pages/Maps/list.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AR_Navigation.Pages.Maps
{
    public class listModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<listModel> _logger;


        public listModel(IWebHostEnvironment webHostEnvironment, ILogger<listModel> logger)
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public async Task<IActionResult> OnPostCreateMapAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Map");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Maps/list");
        }

        public async Task<IActionResult> OnPostEditMapAsync()
        {

            string imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Map");

            string uniqueFileName = null;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                uniqueFileName = ImageFile.FileName;

                string filePath = Path.Combine(imagesDirectory, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            _logger.LogInformation($"Images directory: {imagesDirectory}");


            return RedirectToPage("/Maps/list");
        }
    }
}

SEP490_G41/AR_Navigation/Pages/Mappoints/detail.cshtml
@page "{id:int}"
@model AR_Navigation.Pages.Mappoints.detailModel
@{
    Layout = "_AdminLayout";
}
<head>

</head>
<style>
   
    .img-magnifier-glass {
        position: absolute;
        border: 3px solid #000;
        border-radius: 50%;
        cursor: none;
        width: 100px;
        height: 100px;
    }

    .mappoint-image {
        width: 800px; /* Thay đổi kích thước rộng */
        height: 400px; /* Thay đổi kích thước cao */
        
        margin-top: 10px;
    }

        .mappoint-image img {
            max-width: 100%;
            max-height: 100%;
            border-radius: 8px;
        }

    canvas {
        width: 100%;
        background-position: center;
        background-size: 100%;
        background-clip: border-box;
        background-repeat: no-repeat;
    }
</style>
<div class="page-header no-gutters">
    <h1>Mappoint Detail</h1>
    <div class="row align-items-md-center">
        <div class="col-md-12">
            <div class="text-md-right m-v-10" id="button-change">
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="selected-image-container" id="map-images-container">
        <canvas id="canvas_data" width="1065%"
                onclick="pixelLocation(event), databaseLocation(event)">
        </canvas>
    </div>
    <div class="mappoint-image">
        <img id="mappoint-image" src="" alt="Mappoint Image">
    </div>
    <div class="text-md-right m-v-10" id="button-change">
        <button id="edit-btn" class="btn btn-primary">Edit</button>
        <button id="delete-btn" class="btn btn-danger">Delete</button>
    </div>
    <div id="edit-form" style="display: none;">
        <h3>Edit Mappoint</h3>
        <form asp-page="/Mappoints/detail" asp-page-handler="EditMappoint" id="form-edit-mapapoint" method="post" enctype="multipart/form-data">
            <input type="hidden" class="form-control" id="mappointID" name="name">
            <input type="hidden" class="form-control" id="mapID" name="name">
            <input type="hidden" class="form-control" id="floorID" name="name">
            <input type="hidden" class="form-control" id="buildingID" name="name">
            <input type="hidden" class="form-control" id="locationGPS" name="name">

            <div class="form-group">
                <label for="name">Mappoint Name:</label>
                <input type="text" class="form-control" id="mappointName" name="name"> 
            </div> 
            <div class="form-group"> 
                <label for="locationWeb">Location Web (Tọa độ trên ảnh):</label> 
                <input type="text" class="form-control" id="locationWeb" name="locationWeb" readonly> 
            </div> 
            <div class="form-group">
                <label for="locationApp">Location App (Tọa độ trên database):</label> 
                <input type="text" class="form-control" id="locationApp" name="locationApp" readonly> 
            </div>
            <div class="form-group">
                <div class="custom-file">
                    <input type="file" name="ImageFile" class="custom-file-input" id="edit-map-image" aria-describedby="inputGroupFileAddon">
                    <label class="custom-file-label" for="edit-map-image">Choose file</label>
                </div>
            </div>
            <!-- Thêm các trường khác tùy theo yêu cầu -->
            <button type="button" id="save-btn" class="btn btn-primary">Save</button>
            <button type="button" id="cancel-btn" class="btn btn-secondary">Cancel</button>
        </form>
    </div>
</div>

<!-- Content Wrapper END -->
@* Modal Map Image*@
<script src="/js/detailMappoint.js"></script>
<script>


    $(document).ready(function () {
        var mappointId = window.location.pathname.split("/").pop();

        $('#edit-btn').click(function () {
            // Hiển thị form chỉnh sửa
            $('#edit-form').show();
            newMappoint();
            // Lấy thông tin mappoint từ API và điền vào form
            $.ajax({
                url: `https://finnsapi.developvn.click/api/mappoints/${mappointId}`,
                type: 'GET',
                dataType: 'json',
                success: function (mapPoint) {
                    $('#mappointID').val(mapPoint.mapPointId);
                    $('#mapID').val(mapPoint.mapId);
                    $('#floorID').val(mapPoint.floorId);
                    $('#buildingID').val(mapPoint.buildingId);
                    $('#locationGPS').val(mapPoint.locationGps);
                    $('#mappointName').val(mapPoint.mappointName);
                    $('#locationWeb').val(mapPoint.locationWeb);
                    $('#locationApp').val(mapPoint.locationApp);
                    $('#edit-map-image').val(mapPoint.image);
                },
                error: function (xhr, status, error) {
                    console.log('Error loading mappoint from API: ' + error);
                }
            });
        });

        $('#save-btn').click(function () {
            // Lấy dữ liệu từ form
            const mappointId = $('#mappointID').val();
            const mapId = $('#mapID').val();
            const name = $('#mappointName').val();
            const locationWeb = $('#locationWeb').val();
            const locationApp = $('#locationApp').val();
            const locationGps = "[0,0]"; // Nếu không có giá trị, đặt là null
            const floorId = $('#floorID').val();
            const buildingId = $('#buildingID').val();
            const image = $('#edit-map-image')[0].files[0]; // Lấy file ảnh từ input file

            // Tạo một FormData để gửi dữ liệu và file ảnh
            const formData = new FormData();
            formData.append('mapPointId', mappointId);
            formData.append('mapId', mapId);
            formData.append('MappointName', name);
            formData.append('LocationWeb', locationWeb);
            formData.append('LocationApp', locationApp);
            formData.append('LocationGps', locationGps);
            formData.append('FloorId', floorId);
            formData.append('BuildingId', buildingId);

            if (image) {
                // Nếu người dùng đã chọn ảnh mới, thêm ảnh mới vào FormData
                formData.append('Image', image);
            } else {
                // Nếu không có ảnh mới, gửi tên của ảnh cũ để lấy ảnh cũ từ server
                formData.append('Image', originalImageFileName);
            }

            // Gửi dữ liệu lên API
            $.ajax({
                url: `https://finnsapi.developvn.click/api/mappoints/${mappointId}`,
                type: 'PUT',
                data: formData,
                contentType: false,
                processData: false,
                success: function (response) {
                    console.log('Mappoint updated successfully');
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: 'Map point update successfully!'
                    }).then(function () {
                        $('#form-edit-mapapoint').submit();
                    });
                    $('#edit-form').hide();
                },
                error: function (xhr, status, error) {
                    console.log('Error updating mappoint: ' + error);
                    console.log('Mappoint updated successfully ' + originalImageFileName);
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: 'Failed to update map point. Please try again later.'
                    });
                }
            });
        });

        // Function to handle click event on Delete button
        $('#delete-btn').click(function () {
            Swal.fire({
                title: 'Are you sure?',
                text: 'You will not be able to recover this MapPoint!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: `https://finnsapi.developvn.click/api/mappoints/${mappointId}`,
                        type: 'DELETE',
                        success: function (response) {
                            Swal.fire(
                                'Deleted!',
                                'MapPoint has been deleted.',
                                'success'
                            ).then(() => {
                                window.location.href = '/Mappoints/list';
                            });
                        },
                        error: function (xhr, status, error) {
                            Swal.fire(
                                'Error!',
                                'Failed to delete MapPoint. Please try again later.',
                                'error'
                            );
                        }
                    });
                }
            });
        });

        $('#cancel-btn').click(function () {
            // Ẩn form chỉnh sửa
            undo();
            $('#edit-form').hide();
            $('#mappoint-image').attr('src', originalImageSrc); // Đặt lại ảnh về ảnh ban đầu
        });

    });





    let originalImageSrc = '';
    let originalImageFileName = '';
    $(document).ready(function () {
        //session
        var userJson = sessionStorage.getItem('user');
        if (!userJson) {
            window.location.href = '/Authen/Login';
        } else {
            var user = JSON.parse(userJson);
            if (user.status !== "active") {
                // Display SweetAlert message
                Swal.fire({
                    icon: 'error',
                    title: 'Access Denied',
                    text: 'You do not have permission to access this page.',
                    showConfirmButton: false,
                    timer: 2000 // Close the alert after 2 seconds
                }).then((result) => {
                    // Redirect to login page after the alert is closed
                    window.location.href = '/HomePage/Home';
                });
            }
        }
        var mappointId = window.location.pathname.split("/").pop();

        $.ajax({
            url: `https://finnsapi.developvn.click/api/mappoints/${mappointId}`,
            type: 'GET',
            dataType: 'json',
            success: function (mapPoint) {
                    const mapId = mapPoint.mapId;
                    originalImageSrc = `/Images/Mappoint/${mapPoint.image}`;
                    originalImageFileName = mapPoint.image;// Lưu đường dẫn ảnh ban đầu
                     $('#mappoint-image').attr('src', originalImageSrc);
                // Gọi API để lấy thông tin map theo mapId
                    $.ajax({
                    url: `https://finnsapi.developvn.click/api/maps/${mapId}`,
                        type: 'GET',
                        dataType: 'json',
                        success: function (map) {
                            // Lấy mapImage2D từ map
                            const mapImage2D = map.mapImage2D;
                            getMapPointsByMapId(map.mapId, mappointId);
                            // Sử dụng mapImage2D để hiển thị ảnh
                            var imageSrc = `/Images/Map/${mapImage2D}`;
                            var canvas = document.getElementById('canvas_data');
                            canvas.style.backgroundImage = `url(${imageSrc})`;
                        },
                        error: function (xhr, status, error) {
                            console.log('Error loading map from API: ' + error);
                        }
                    });
            },
            error: function (xhr, status, error) {
                console.log('Error loading map points from API: ' + error);
            }
        });
    });

    $('#edit-map-image').on('change', function () {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function () {
                $('#mappoint-image').attr('src', reader.result);
            }
            reader.readAsDataURL(file);
        }
    });


   


</script>